---
version: "2"

services:
  commander:
    image: astronomerinc/ap-commander
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      io.astronomer.docker: "true"
    ports:
      - "8880:8880"
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      COMMANDER_PORT: 8880
      COMMANDER_KUBE_CONFIG: /root/.kube/config
