version: "2"

services:
  commander:
    image: astronomerinc/ap-commander
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:8880"
      - "50051:50051"
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      COMMANDER_KUBECONFIG: /root/.kube/config
      ENVIRONMENT: development
      GRPC_TRACE: all
      GRPC_VERBOSITY: DEBUG
      COMMANDER_HELM_REPO: "https://helm.astronomer.io"
      COMMANDER_TILLER_HOST: "docker.for.mac.localhost:44134"
