---
version: "2"

services:
  commander:
    image: astronomerinc/ap-pce-commander
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8880:8880"
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ~/.config/gcloud:/root/.config/gcloud
    environment:
      COMMANDER_KUBE_CONFIG: /root/.kube/config
