---
version: "2"

services:
  commander:
    image: astronomerinc/ap-pce-commander
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8880:8880"
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ~/.config/gcloud:/root/.config/gcloud
      - /Users/macbook/.minikube/:/Users/macbook/.minikube/
    environment:
      COMMANDER_KUBECONFIG: /root/.kube/config
      ENVIRONMENT: development
      COMMANDER_KUBE_CORE_NAMESPACE: "astro-core"
      COMMANDER_KUBE_AIRFLOW_NAMESPACE: "astro-airflow"
      COMMANDER_KUBE_CLICKSTREAM_NAMESPACE: "astro-clickstream"