---
version: "2"

services:
  commander:
    image: astronomerinc/ap-pce-commander
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:8880"
      - "50051:50051"
    volumes:
      - ~/.kube/config:/root/.kube/config
      - ~/.config/gcloud:/root/.config/gcloud
      - /Users/macbook/.minikube/:/Users/macbook/.minikube/
    environment:
      COMMANDER_KUBECONFIG: /root/.kube/config
      ENVIRONMENT: development
      GRPC_TRACE: all
      GRPC_VERBOSITY: DEBUG
      COMMANDER_KUBE_NAMESPACE: "cj-dev-test"
      COMMANDER_HELM_REPO: "http://docker.for.mac.localhost:11000/repo"