[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.15"

[[constraint]]
  name = "helm.sh/helm"
  version = "v3.0.0-alpha.2"

[[override]]
  name = "sigs.k8s.io/kustomize"
  version = "2.0.3"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.15"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.15"

# This override below necessary for using docker/distribution as a test dependency
[[override]]
  name = "rsc.io/letsencrypt"
  branch = "master"
  source = "https://github.com/dmcgowan/letsencrypt.git"

[[override]]
  name = "github.com/docker/distribution"
  revision = "40b7b5830a2337bb07627617740c0e39eb92800c"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "05f3235734ad95d0016f6a23902f06461fcf567a"

[[override]]
  name = "github.com/docker/docker"
  revision = "2cb26cfe9cbf8a64c5046c74d65f4528b22e67f4"

[[override]]
  name = "k8s.io/cli-runtime"
  revision = "44a48934c135b31e4f1c0d12e91d384e1cb2304c"