[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "helm.sh/helm"
  version = "v3.0.0-alpha.1"

[[override]]
  name = "github.com/docker/docker"
  source = "https://github.com/docker/engine.git"
  revision = "200b524eff60a9c95a22bc2518042ac2ff617d07" # 18.09 branch

[[override]]
  name = "github.com/docker/distribution"
  revision = "6664ec703991875e14419ff4960921cce7678bab"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "fc3b03a2d2d1f43fad3007038bd16f044f870722"
