version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Component test
          command: /bin/bash .circleci/component_test.sh
