// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commander.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	commander.proto
	common.proto
	deployment.proto

It has these top-level messages:
	PingRequest
	PingResponse
	UUID
	Env
	EnvSecret
	Secret
	Result
	Chart
	Deployment
	GetDeploymentRequest
	GetDeploymentResponse
	CreateDeploymentRequest
	CreateDeploymentResponse
	UpdateDeploymentRequest
	UpdateDeploymentResponse
	UpgradeDeploymentRequest
	UpgradeDeploymentResponse
	DeleteDeploymentRequest
	DeleteDeploymentResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Commander service

type CommanderClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*GetDeploymentResponse, error)
	CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*CreateDeploymentResponse, error)
	UpdateDeployment(ctx context.Context, in *UpdateDeploymentRequest, opts ...grpc.CallOption) (*UpdateDeploymentResponse, error)
	UpgradeDeployment(ctx context.Context, in *UpgradeDeploymentRequest, opts ...grpc.CallOption) (*UpgradeDeploymentResponse, error)
	DeleteDeployment(ctx context.Context, in *DeleteDeploymentRequest, opts ...grpc.CallOption) (*DeleteDeploymentResponse, error)
}

type commanderClient struct {
	cc *grpc.ClientConn
}

func NewCommanderClient(cc *grpc.ClientConn) CommanderClient {
	return &commanderClient{cc}
}

func (c *commanderClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/commander.Commander/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commanderClient) GetDeployment(ctx context.Context, in *GetDeploymentRequest, opts ...grpc.CallOption) (*GetDeploymentResponse, error) {
	out := new(GetDeploymentResponse)
	err := grpc.Invoke(ctx, "/commander.Commander/GetDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commanderClient) CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*CreateDeploymentResponse, error) {
	out := new(CreateDeploymentResponse)
	err := grpc.Invoke(ctx, "/commander.Commander/CreateDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commanderClient) UpdateDeployment(ctx context.Context, in *UpdateDeploymentRequest, opts ...grpc.CallOption) (*UpdateDeploymentResponse, error) {
	out := new(UpdateDeploymentResponse)
	err := grpc.Invoke(ctx, "/commander.Commander/UpdateDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commanderClient) UpgradeDeployment(ctx context.Context, in *UpgradeDeploymentRequest, opts ...grpc.CallOption) (*UpgradeDeploymentResponse, error) {
	out := new(UpgradeDeploymentResponse)
	err := grpc.Invoke(ctx, "/commander.Commander/UpgradeDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commanderClient) DeleteDeployment(ctx context.Context, in *DeleteDeploymentRequest, opts ...grpc.CallOption) (*DeleteDeploymentResponse, error) {
	out := new(DeleteDeploymentResponse)
	err := grpc.Invoke(ctx, "/commander.Commander/DeleteDeployment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Commander service

type CommanderServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetDeployment(context.Context, *GetDeploymentRequest) (*GetDeploymentResponse, error)
	CreateDeployment(context.Context, *CreateDeploymentRequest) (*CreateDeploymentResponse, error)
	UpdateDeployment(context.Context, *UpdateDeploymentRequest) (*UpdateDeploymentResponse, error)
	UpgradeDeployment(context.Context, *UpgradeDeploymentRequest) (*UpgradeDeploymentResponse, error)
	DeleteDeployment(context.Context, *DeleteDeploymentRequest) (*DeleteDeploymentResponse, error)
}

func RegisterCommanderServer(s *grpc.Server, srv CommanderServer) {
	s.RegisterService(&_Commander_serviceDesc, srv)
}

func _Commander_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commander.Commander/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commander_GetDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).GetDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commander.Commander/GetDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).GetDeployment(ctx, req.(*GetDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commander_CreateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).CreateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commander.Commander/CreateDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).CreateDeployment(ctx, req.(*CreateDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commander_UpdateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).UpdateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commander.Commander/UpdateDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).UpdateDeployment(ctx, req.(*UpdateDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commander_UpgradeDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).UpgradeDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commander.Commander/UpgradeDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).UpgradeDeployment(ctx, req.(*UpgradeDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commander_DeleteDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).DeleteDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commander.Commander/DeleteDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).DeleteDeployment(ctx, req.(*DeleteDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commander_serviceDesc = grpc.ServiceDesc{
	ServiceName: "commander.Commander",
	HandlerType: (*CommanderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Commander_Ping_Handler,
		},
		{
			MethodName: "GetDeployment",
			Handler:    _Commander_GetDeployment_Handler,
		},
		{
			MethodName: "CreateDeployment",
			Handler:    _Commander_CreateDeployment_Handler,
		},
		{
			MethodName: "UpdateDeployment",
			Handler:    _Commander_UpdateDeployment_Handler,
		},
		{
			MethodName: "UpgradeDeployment",
			Handler:    _Commander_UpgradeDeployment_Handler,
		},
		{
			MethodName: "DeleteDeployment",
			Handler:    _Commander_DeleteDeployment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commander.proto",
}

func init() { proto1.RegisterFile("commander.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x48,
	0xf1, 0x80, 0x98, 0xf9, 0x79, 0x10, 0x09, 0x29, 0x81, 0x94, 0xd4, 0x82, 0x9c, 0xfc, 0xca, 0xdc,
	0xd4, 0xbc, 0x12, 0x88, 0x88, 0xd1, 0x6c, 0x16, 0x2e, 0x4e, 0x67, 0x98, 0x6a, 0x21, 0x4b, 0x2e,
	0x96, 0x80, 0xcc, 0xbc, 0x74, 0x21, 0x31, 0x3d, 0x84, 0x91, 0x20, 0x81, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x29, 0x71, 0x0c, 0xf1, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x25, 0x06, 0xa1,
	0x10, 0x2e, 0x5e, 0xf7, 0xd4, 0x12, 0x17, 0xb8, 0xf9, 0x42, 0xf2, 0x48, 0x6a, 0x51, 0x64, 0x60,
	0x86, 0x29, 0xe0, 0x56, 0x00, 0x37, 0x35, 0x96, 0x4b, 0xc0, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15,
	0xc9, 0x60, 0x25, 0x24, 0x7d, 0xe8, 0x92, 0x30, 0xb3, 0x95, 0xf1, 0xaa, 0x41, 0x36, 0x3e, 0xb4,
	0x20, 0x05, 0xb7, 0xf1, 0xe8, 0x92, 0xd8, 0x8c, 0xc7, 0x54, 0x03, 0x37, 0x3e, 0x81, 0x4b, 0x30,
	0xb4, 0x20, 0xbd, 0x28, 0x31, 0x05, 0xd9, 0x7c, 0x54, 0xbd, 0x68, 0xb2, 0x30, 0x0b, 0x54, 0xf0,
	0x2b, 0x42, 0xf6, 0x80, 0x4b, 0x6a, 0x4e, 0x2a, 0x4e, 0x0f, 0xa0, 0x4b, 0x62, 0xf3, 0x00, 0xa6,
	0x1a, 0x98, 0xf1, 0x4e, 0xec, 0x51, 0xac, 0xe0, 0x64, 0x92, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x07, 0x0e, 0x9d, 0x18, 0x6b, 0x02, 0x00, 0x00,
}
