// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetDeploymentRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetDeploymentRequest) Reset()                    { *m = GetDeploymentRequest{} }
func (m *GetDeploymentRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetDeploymentRequest) ProtoMessage()               {}
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *GetDeploymentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetDeploymentResponse struct {
	Result      *Result       `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Deployments []*Deployment `protobuf:"bytes,2,rep,name=deployments" json:"deployments,omitempty"`
}

func (m *GetDeploymentResponse) Reset()                    { *m = GetDeploymentResponse{} }
func (m *GetDeploymentResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetDeploymentResponse) ProtoMessage()               {}
func (*GetDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GetDeploymentResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetDeploymentResponse) GetDeployments() []*Deployment {
	if m != nil {
		return m.Deployments
	}
	return nil
}

type CreateDeploymentRequest struct {
	ReleaseName string       `protobuf:"bytes,1,opt,name=release_name,json=releaseName" json:"release_name,omitempty"`
	RawConfig   string       `protobuf:"bytes,2,opt,name=raw_config,json=rawConfig" json:"raw_config,omitempty"`
	Chart       *Chart       `protobuf:"bytes,3,opt,name=chart" json:"chart,omitempty"`
	Namespace   string       `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
	Secrets     []*Secret    `protobuf:"bytes,10,rep,name=secrets" json:"secrets,omitempty"`
	EnvSecret   []*EnvSecret `protobuf:"bytes,11,rep,name=env_secret,json=envSecret" json:"env_secret,omitempty"`
}

func (m *CreateDeploymentRequest) Reset()                    { *m = CreateDeploymentRequest{} }
func (m *CreateDeploymentRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateDeploymentRequest) ProtoMessage()               {}
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *CreateDeploymentRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *CreateDeploymentRequest) GetRawConfig() string {
	if m != nil {
		return m.RawConfig
	}
	return ""
}

func (m *CreateDeploymentRequest) GetChart() *Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *CreateDeploymentRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateDeploymentRequest) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *CreateDeploymentRequest) GetEnvSecret() []*EnvSecret {
	if m != nil {
		return m.EnvSecret
	}
	return nil
}

type CreateDeploymentResponse struct {
	Result     *Result     `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Deployment *Deployment `protobuf:"bytes,2,opt,name=deployment" json:"deployment,omitempty"`
}

func (m *CreateDeploymentResponse) Reset()                    { *m = CreateDeploymentResponse{} }
func (m *CreateDeploymentResponse) String() string            { return proto1.CompactTextString(m) }
func (*CreateDeploymentResponse) ProtoMessage()               {}
func (*CreateDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *CreateDeploymentResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateDeploymentResponse) GetDeployment() *Deployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type UpdateDeploymentRequest struct {
	ReleaseName      string       `protobuf:"bytes,1,opt,name=release_name,json=releaseName" json:"release_name,omitempty"`
	RawConfig        string       `protobuf:"bytes,2,opt,name=raw_config,json=rawConfig" json:"raw_config,omitempty"`
	Chart            *Chart       `protobuf:"bytes,3,opt,name=chart" json:"chart,omitempty"`
	OrganizationUuid *UUID        `protobuf:"bytes,6,opt,name=organization_uuid,json=organizationUuid" json:"organization_uuid,omitempty"`
	Secrets          []*Secret    `protobuf:"bytes,10,rep,name=secrets" json:"secrets,omitempty"`
	EnvSecret        []*EnvSecret `protobuf:"bytes,11,rep,name=env_secret,json=envSecret" json:"env_secret,omitempty"`
}

func (m *UpdateDeploymentRequest) Reset()                    { *m = UpdateDeploymentRequest{} }
func (m *UpdateDeploymentRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateDeploymentRequest) ProtoMessage()               {}
func (*UpdateDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *UpdateDeploymentRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *UpdateDeploymentRequest) GetRawConfig() string {
	if m != nil {
		return m.RawConfig
	}
	return ""
}

func (m *UpdateDeploymentRequest) GetChart() *Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *UpdateDeploymentRequest) GetOrganizationUuid() *UUID {
	if m != nil {
		return m.OrganizationUuid
	}
	return nil
}

func (m *UpdateDeploymentRequest) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *UpdateDeploymentRequest) GetEnvSecret() []*EnvSecret {
	if m != nil {
		return m.EnvSecret
	}
	return nil
}

type UpdateDeploymentResponse struct {
	Result     *Result     `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Deployment *Deployment `protobuf:"bytes,2,opt,name=deployment" json:"deployment,omitempty"`
}

func (m *UpdateDeploymentResponse) Reset()                    { *m = UpdateDeploymentResponse{} }
func (m *UpdateDeploymentResponse) String() string            { return proto1.CompactTextString(m) }
func (*UpdateDeploymentResponse) ProtoMessage()               {}
func (*UpdateDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *UpdateDeploymentResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *UpdateDeploymentResponse) GetDeployment() *Deployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type UpgradeDeploymentRequest struct {
	ReleaseName string       `protobuf:"bytes,1,opt,name=release_name,json=releaseName" json:"release_name,omitempty"`
	RawConfig   string       `protobuf:"bytes,2,opt,name=raw_config,json=rawConfig" json:"raw_config,omitempty"`
	Chart       *Chart       `protobuf:"bytes,3,opt,name=chart" json:"chart,omitempty"`
	Secrets     []*Secret    `protobuf:"bytes,10,rep,name=secrets" json:"secrets,omitempty"`
	EnvSecret   []*EnvSecret `protobuf:"bytes,11,rep,name=env_secret,json=envSecret" json:"env_secret,omitempty"`
}

func (m *UpgradeDeploymentRequest) Reset()                    { *m = UpgradeDeploymentRequest{} }
func (m *UpgradeDeploymentRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpgradeDeploymentRequest) ProtoMessage()               {}
func (*UpgradeDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *UpgradeDeploymentRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *UpgradeDeploymentRequest) GetRawConfig() string {
	if m != nil {
		return m.RawConfig
	}
	return ""
}

func (m *UpgradeDeploymentRequest) GetChart() *Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *UpgradeDeploymentRequest) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *UpgradeDeploymentRequest) GetEnvSecret() []*EnvSecret {
	if m != nil {
		return m.EnvSecret
	}
	return nil
}

type UpgradeDeploymentResponse struct {
	Result     *Result     `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Deployment *Deployment `protobuf:"bytes,2,opt,name=deployment" json:"deployment,omitempty"`
}

func (m *UpgradeDeploymentResponse) Reset()                    { *m = UpgradeDeploymentResponse{} }
func (m *UpgradeDeploymentResponse) String() string            { return proto1.CompactTextString(m) }
func (*UpgradeDeploymentResponse) ProtoMessage()               {}
func (*UpgradeDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *UpgradeDeploymentResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *UpgradeDeploymentResponse) GetDeployment() *Deployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type DeleteDeploymentRequest struct {
	ReleaseName     string `protobuf:"bytes,1,opt,name=release_name,json=releaseName" json:"release_name,omitempty"`
	Namespace       string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	DeleteNamespace bool   `protobuf:"varint,5,opt,name=delete_namespace,json=deleteNamespace" json:"delete_namespace,omitempty"`
}

func (m *DeleteDeploymentRequest) Reset()                    { *m = DeleteDeploymentRequest{} }
func (m *DeleteDeploymentRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDeploymentRequest) ProtoMessage()               {}
func (*DeleteDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *DeleteDeploymentRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *DeleteDeploymentRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeleteDeploymentRequest) GetDeleteNamespace() bool {
	if m != nil {
		return m.DeleteNamespace
	}
	return false
}

type DeleteDeploymentResponse struct {
	Result     *Result     `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Deployment *Deployment `protobuf:"bytes,2,opt,name=deployment" json:"deployment,omitempty"`
}

func (m *DeleteDeploymentResponse) Reset()                    { *m = DeleteDeploymentResponse{} }
func (m *DeleteDeploymentResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteDeploymentResponse) ProtoMessage()               {}
func (*DeleteDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *DeleteDeploymentResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *DeleteDeploymentResponse) GetDeployment() *Deployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

func init() {
	proto1.RegisterType((*GetDeploymentRequest)(nil), "commander.GetDeploymentRequest")
	proto1.RegisterType((*GetDeploymentResponse)(nil), "commander.GetDeploymentResponse")
	proto1.RegisterType((*CreateDeploymentRequest)(nil), "commander.CreateDeploymentRequest")
	proto1.RegisterType((*CreateDeploymentResponse)(nil), "commander.CreateDeploymentResponse")
	proto1.RegisterType((*UpdateDeploymentRequest)(nil), "commander.UpdateDeploymentRequest")
	proto1.RegisterType((*UpdateDeploymentResponse)(nil), "commander.UpdateDeploymentResponse")
	proto1.RegisterType((*UpgradeDeploymentRequest)(nil), "commander.UpgradeDeploymentRequest")
	proto1.RegisterType((*UpgradeDeploymentResponse)(nil), "commander.UpgradeDeploymentResponse")
	proto1.RegisterType((*DeleteDeploymentRequest)(nil), "commander.DeleteDeploymentRequest")
	proto1.RegisterType((*DeleteDeploymentResponse)(nil), "commander.DeleteDeploymentResponse")
}

func init() { proto1.RegisterFile("deployment.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x95, 0x6c, 0xed, 0xc8, 0x9b, 0x49, 0xeb, 0xac, 0x4d, 0x35, 0x08, 0xa4, 0x92, 0x03,
	0xea, 0x40, 0xea, 0x61, 0x13, 0xe2, 0xc2, 0x89, 0x16, 0x21, 0x2e, 0x3b, 0x18, 0xe5, 0xc2, 0x25,
	0x32, 0xc9, 0x4b, 0x89, 0x94, 0xd8, 0xc1, 0x76, 0x36, 0xf1, 0xef, 0x84, 0xf8, 0x24, 0x7c, 0x37,
	0x3e, 0x07, 0x8a, 0xd3, 0x3f, 0x66, 0x81, 0x03, 0x48, 0xa4, 0xa7, 0xba, 0xcf, 0xfb, 0xb3, 0xfd,
	0xfa, 0x79, 0x12, 0x07, 0x46, 0x19, 0x56, 0x85, 0xfc, 0x50, 0xa2, 0x30, 0xb3, 0x4a, 0x49, 0x23,
	0x49, 0x90, 0xca, 0xb2, 0xe4, 0x22, 0x43, 0x75, 0xe7, 0xb0, 0x19, 0x4a, 0xd1, 0x16, 0xa2, 0x87,
	0x70, 0xf2, 0x02, 0xcd, 0x62, 0xc3, 0x33, 0x7c, 0x5f, 0xa3, 0x36, 0x84, 0xc0, 0xbe, 0xe0, 0x25,
	0x52, 0x6f, 0xe2, 0x4d, 0x03, 0x66, 0xc7, 0xd1, 0x27, 0x38, 0xbd, 0xc1, 0xea, 0x4a, 0x0a, 0x8d,
	0xe4, 0x0c, 0x86, 0x0a, 0x75, 0x5d, 0x18, 0x8b, 0x87, 0xe7, 0xc7, 0xb3, 0xcd, 0x76, 0x33, 0x66,
	0x0b, 0x6c, 0x05, 0x90, 0x27, 0x10, 0x6e, 0x9b, 0xd3, 0xd4, 0x9f, 0xec, 0x4d, 0xc3, 0xf3, 0x53,
	0x87, 0x77, 0x96, 0x77, 0xc9, 0xe8, 0xab, 0x0f, 0xe3, 0xb9, 0x42, 0x6e, 0xb0, 0xdb, 0xec, 0x7d,
	0x38, 0x54, 0x58, 0x20, 0xd7, 0x98, 0x38, 0x4d, 0x87, 0x2b, 0xed, 0x92, 0x97, 0x48, 0xee, 0x01,
	0x28, 0x7e, 0x9d, 0xa4, 0x52, 0xbc, 0xcd, 0x97, 0xd4, 0xb7, 0x40, 0xa0, 0xf8, 0xf5, 0xdc, 0x0a,
	0xe4, 0x01, 0x0c, 0xd2, 0x77, 0x5c, 0x19, 0xba, 0x67, 0x0f, 0x30, 0x72, 0x1a, 0x9a, 0x37, 0x3a,
	0x6b, 0xcb, 0xe4, 0x2e, 0x04, 0xcd, 0x0e, 0xba, 0xe2, 0x29, 0xd2, 0xfd, 0x76, 0x95, 0x8d, 0x40,
	0x1e, 0xc1, 0x81, 0xc6, 0x54, 0xa1, 0xd1, 0x14, 0xec, 0xc1, 0x5c, 0x23, 0x5e, 0xd9, 0x0a, 0x5b,
	0x13, 0xe4, 0x02, 0x00, 0xc5, 0x55, 0xd2, 0xfe, 0xa5, 0xa1, 0xe5, 0x4f, 0x1c, 0xfe, 0xb9, 0xb8,
	0x5a, 0x4d, 0x09, 0x70, 0x3d, 0x8c, 0x3e, 0x03, 0xed, 0x9a, 0xf0, 0xf7, 0x29, 0x3c, 0x06, 0xd8,
	0x7a, 0x6b, 0xdd, 0xf8, 0x63, 0x08, 0x0e, 0x18, 0x7d, 0xf7, 0x61, 0x1c, 0x57, 0xd9, 0x8e, 0x33,
	0x78, 0x0a, 0xc7, 0x52, 0x2d, 0xb9, 0xc8, 0x3f, 0x72, 0x93, 0x4b, 0x91, 0xd4, 0x75, 0x9e, 0xd1,
	0xa1, 0x9d, 0x73, 0xe4, 0xcc, 0x89, 0xe3, 0x97, 0x0b, 0x36, 0x72, 0xc9, 0xb8, 0xce, 0xb3, 0x7e,
	0x32, 0xea, 0x9a, 0xd4, 0x5b, 0x46, 0x3f, 0xbc, 0x66, 0xfb, 0xa5, 0xe2, 0xd9, 0x4e, 0x43, 0xfa,
	0xff, 0x36, 0x7f, 0x81, 0xdb, 0xbf, 0x39, 0x67, 0x6f, 0x3e, 0x7f, 0xf3, 0x60, 0xbc, 0xc0, 0x02,
	0xff, 0xf1, 0x5d, 0xf8, 0xe5, 0x22, 0xf1, 0x6f, 0x5e, 0x24, 0x67, 0xcd, 0x15, 0xde, 0xac, 0x9d,
	0x6c, 0xa1, 0xc1, 0xc4, 0x9b, 0xde, 0x62, 0x47, 0xad, 0x7e, 0xb9, 0x96, 0x9b, 0xa7, 0xad, 0xdb,
	0x46, 0x5f, 0x2e, 0x3c, 0x3b, 0x78, 0x3d, 0xb0, 0xdf, 0x91, 0x37, 0x43, 0xfb, 0x73, 0xf1, 0x33,
	0x00, 0x00, 0xff, 0xff, 0x2f, 0x02, 0xa0, 0x43, 0x7b, 0x06, 0x00, 0x00,
}
