// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListDeploymentsRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListDeploymentsRequest) Reset()                    { *m = ListDeploymentsRequest{} }
func (m *ListDeploymentsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDeploymentsRequest) ProtoMessage()               {}
func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ListDeploymentsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListDeploymentsResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListDeploymentsResponse) Reset()                    { *m = ListDeploymentsResponse{} }
func (m *ListDeploymentsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDeploymentsResponse) ProtoMessage()               {}
func (*ListDeploymentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ListDeploymentsResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateDeploymentRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateDeploymentRequest) Reset()                    { *m = CreateDeploymentRequest{} }
func (m *CreateDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDeploymentRequest) ProtoMessage()               {}
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CreateDeploymentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateDeploymentResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateDeploymentResponse) Reset()                    { *m = CreateDeploymentResponse{} }
func (m *CreateDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDeploymentResponse) ProtoMessage()               {}
func (*CreateDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *CreateDeploymentResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateDeploymentRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UpdateDeploymentRequest) Reset()                    { *m = UpdateDeploymentRequest{} }
func (m *UpdateDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeploymentRequest) ProtoMessage()               {}
func (*UpdateDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *UpdateDeploymentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateDeploymentResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UpdateDeploymentResponse) Reset()                    { *m = UpdateDeploymentResponse{} }
func (m *UpdateDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateDeploymentResponse) ProtoMessage()               {}
func (*UpdateDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *UpdateDeploymentResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpgradeDeploymentRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UpgradeDeploymentRequest) Reset()                    { *m = UpgradeDeploymentRequest{} }
func (m *UpgradeDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*UpgradeDeploymentRequest) ProtoMessage()               {}
func (*UpgradeDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *UpgradeDeploymentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpgradeDeploymentResponse struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UpgradeDeploymentResponse) Reset()                    { *m = UpgradeDeploymentResponse{} }
func (m *UpgradeDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*UpgradeDeploymentResponse) ProtoMessage()               {}
func (*UpgradeDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *UpgradeDeploymentResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteDeploymentRequest struct {
	ReleaseName string `protobuf:"bytes,1,opt,name=release_name,json=releaseName" json:"release_name,omitempty"`
}

func (m *DeleteDeploymentRequest) Reset()                    { *m = DeleteDeploymentRequest{} }
func (m *DeleteDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDeploymentRequest) ProtoMessage()               {}
func (*DeleteDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *DeleteDeploymentRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

type DeleteDeploymentResponse struct {
	ReleaseName string `protobuf:"bytes,1,opt,name=release_name,json=releaseName" json:"release_name,omitempty"`
}

func (m *DeleteDeploymentResponse) Reset()                    { *m = DeleteDeploymentResponse{} }
func (m *DeleteDeploymentResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDeploymentResponse) ProtoMessage()               {}
func (*DeleteDeploymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *DeleteDeploymentResponse) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func init() {
	proto.RegisterType((*ListDeploymentsRequest)(nil), "commander.ListDeploymentsRequest")
	proto.RegisterType((*ListDeploymentsResponse)(nil), "commander.ListDeploymentsResponse")
	proto.RegisterType((*CreateDeploymentRequest)(nil), "commander.CreateDeploymentRequest")
	proto.RegisterType((*CreateDeploymentResponse)(nil), "commander.CreateDeploymentResponse")
	proto.RegisterType((*UpdateDeploymentRequest)(nil), "commander.UpdateDeploymentRequest")
	proto.RegisterType((*UpdateDeploymentResponse)(nil), "commander.UpdateDeploymentResponse")
	proto.RegisterType((*UpgradeDeploymentRequest)(nil), "commander.UpgradeDeploymentRequest")
	proto.RegisterType((*UpgradeDeploymentResponse)(nil), "commander.UpgradeDeploymentResponse")
	proto.RegisterType((*DeleteDeploymentRequest)(nil), "commander.DeleteDeploymentRequest")
	proto.RegisterType((*DeleteDeploymentResponse)(nil), "commander.DeleteDeploymentResponse")
}

func init() { proto.RegisterFile("deployment.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x49, 0x2d, 0xc8,
	0xc9, 0xaf, 0xcc, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0xce,
	0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x49, 0x2d, 0x52, 0xd2, 0xe1, 0x12, 0xf3, 0xc9, 0x2c, 0x2e, 0x71,
	0x81, 0x2b, 0x29, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x74, 0xb9, 0xc4, 0x31,
	0x54, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0xe2, 0x52, 0xee, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0x8a,
	0xd0, 0x80, 0xcf, 0x74, 0x3d, 0x2e, 0x09, 0x4c, 0xe5, 0xf8, 0x8d, 0x0f, 0x2d, 0x48, 0x21, 0xc5,
	0x78, 0x4c, 0xe5, 0x78, 0x8c, 0x07, 0xab, 0x4f, 0x2f, 0x4a, 0x4c, 0x21, 0xd2, 0x7c, 0x7d, 0x2e,
	0x49, 0x2c, 0xea, 0xf1, 0x58, 0x60, 0xc3, 0x25, 0xee, 0x92, 0x9a, 0x93, 0x8a, 0xcd, 0xfd, 0x8a,
	0x5c, 0x3c, 0x45, 0xa9, 0x39, 0xa9, 0x89, 0xc5, 0xa9, 0xf1, 0x48, 0xda, 0xb8, 0xa1, 0x62, 0x7e,
	0x20, 0xdd, 0xb6, 0x5c, 0x12, 0x98, 0xba, 0xa1, 0xb6, 0x11, 0xd6, 0xee, 0xc4, 0x1a, 0xc5, 0x9c,
	0x58, 0x90, 0x99, 0xc4, 0x06, 0x4e, 0x11, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x70,
	0x08, 0xf0, 0x25, 0x02, 0x00, 0x00,
}
